import {StyleSheet} from 'react-native';
export const styles = StyleSheet.create({
  wrapper:{
    flex:1,
    marginHorizontal:10,
    marginVertical:20,
    zIndex:-1
  },
  row:{
      flexDirection:'row',
      justifyContent:'space-around',
      alignItems:'center',
      borderRadius:1,
      marginVertical:3
  },
  type_name_row:{
      marginRight:20,
  },
  label_txt:{
    fontSize:15,
  },
  type_value_row:{
    width:220,
  },
  skill_field:{
    zIndex:-1,
    marginHorizontal:5,
    marginVertical:20,
    elevation:1,
    borderRadius:1,
  },
  skill_render_items_field:{
    justifyContent:'center',
    alignItems:'center',
    marginTop:10
  },
  my_skill_txt:{
    fontSize:18,
    fontWeight:'600',
    padding:5
  },
  skill_name_txt:{
    fontSize:16,
    fontWeight:'400',
    paddingLeft:5
  },
  render_skill_item_field:{
    flexDirection:'row',
    justifyContent:'space-between',
    padding:10,
    borderRadius:1,
    marginHorizontal:20,
    marginVertical:10,
    elevation:1,
    width:300,
  },
  delete_icon_field:{
    marginLeft:5
  }

});
